id: P006614
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18069
  title: དམ་ཅན་བསྐང་བ།
  author: ''
  volumes:
    f921bbcee81a4766a05c91839151b322:
      image_group_id: I8LS18103
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
